image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache git bash python3 py3-pip docker-compose

stages:
  - test

django:
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  script:
    - docker-compose run --rm django py.test --cov --cov-report term-missing

build:
  stage: test
  script:
    - echo "building..."
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
