image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache git bash python3 py3-pip docker-compose

stages:
  - test
  - build
  - deploy

django:
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  only:
    - develop
    - master
  script:
    - echo "Running tests..."

build:
  stage: build
  only:
    - develop
    - master
  script:
    - echo "Building..."

deploy:
  stage: deploy
  only:
    - master
  script:
    - echo "Deploying..."
