image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache git bash python3 py3-pip make docker-compose

stages:
  - test

django:
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  variables:
    EDIT_SETTINGS: 'no'
  script:
    - docker-compose run --rm django py.test --cov --cov-report term-missing

build:
  stage: test
  when: on_success
  except:
    - template
    - master
    - live
  script:
    - echo "building..."
    - ./scripts/ci.sh live build-only $CI_COMMIT_BRANCH
