image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache bash python3 docker-compose

stages:
  - test
  - build
  - deploy

django:
  stage: test
  only:
    - develop
    - master
  script:
    - echo "Running tests..."

build:
  stage: build
  only:
    - develop
    - master
  script:
    - echo "Building..."
    - ./scripts/ci.sh push

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - echo "Deploying..."
