image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache git bash python3 py3-pip docker-compose

stages:
  - test

django:
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  script:
    - echo "Running tests..."

build:
  stage: test
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
  script:
    - echo "Building..."
