sudo: required
services:
  - docker

before_install:
  - docker build -t alexpetul/terminals-dev -f app/Dockerfile .

script:
  - docker run alexpetul/terminals-dev python -m pytest

after_success:
  - docker build -t alexpetul/terminals .
